
language: python

python:
  - 2.7
  - 3.3


install:
  - sudo apt-get update && sudo apt-get -qq install libhdf5-serial-dev
  - pip install nose numpy six cython
  - pip install h5py
  - python setup.py install

script:
  - nosetests